name: CI Spring Boot

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Run test
        working-directory: services/backend
        run: make test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current date
        run: echo "IMAGE_TAG=$(date -u +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        working-directory: services/backend
        run: |
          docker build -t cicompanion:$IMAGE_TAG .
          docker tag cicompanion:$IMAGE_TAG cicompanion:latest
          docker tag cicompanion:$IMAGE_TAG ${{ secrets.DOCKERHUB_USERNAME }}/cicompanion:$IMAGE_TAG
          docker tag cicompanion:$IMAGE_TAG ${{ secrets.DOCKERHUB_USERNAME }}/cicompanion:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cicompanion:$IMAGE_TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cicompanion:latest
